# Generated by Django 4.0.3 on 2022-03-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0002_post_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
